Took out Windows from the Playwright tests, and fixed MacOS Playwright test command.

diff --git a/.github/workflows/run-playwright-tests.yml b/.github/workflows/run-playwright-tests.yml
--- a/.github/workflows/run-playwright-tests.yml
+++ b/.github/workflows/run-playwright-tests.yml
@@ -7,7 +7,13 @@ jobs:
     strategy:
       fail-fast: false
       matrix:
-        os: [ubuntu-latest, windows-latest, macos-latest]          
+        # We would like to include windows-latest, but it seems to time out the tests
+        # My best guess is that somehow the keypresses are arriving at the terminal job
+        # as the terminal shows "Terminate batch job? (Y/N)" which suggests it is getting
+        # the ctrl-c keypress that is intended for the browser.  But for now, we take it out
+        # because testing on Mac and Ubuntu alone is better than no tests, or tests which
+        # always fail
+        os: [ubuntu-latest, macos-latest]          
     runs-on: ${{ matrix.os }}
     steps:
     - uses: actions/checkout@v4
@@ -17,10 +23,16 @@ jobs:
     - name: Install Playwright Browsers
       run: npx playwright install --with-deps
     - name: Run Playwright tests (Unix)
-      if: ${{ matrix.os != 'windows-latest' }}
+      if: ${{ matrix.os == 'ubuntu-latest' }}
       shell: bash
       run: |
         timeout 3600s npm run test:playwright || echo "Test command exited or timed out"
+    - name: Run Playwright tests (MacOS)
+      if: ${{ matrix.os == 'macos-latest' }}
+      shell: bash
+      run: |
+        brew install coreutils
+        gtimeout 3600s npm run test:playwright || echo "Test command exited or timed out"
     - name: Run Playwright tests (Windows)
       if: ${{ matrix.os == 'windows-latest' }}
       shell: powershell
